/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as CreativesRouteImport } from './routes/creatives'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MoneyRouteImport } from './routes/money'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as TasksRouteImport } from './routes/tasks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const CreativesRoute = CreativesRouteImport.update({
  id: '/creatives',
  path: '/creatives',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MoneyRoute = MoneyRouteImport.update({
  id: '/money',
  path: '/money',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/brands': typeof BrandsRoute
  '/campaigns': typeof CampaignsRoute
  '/creatives': typeof CreativesRoute
  '/login': typeof LoginRoute
  '/money': typeof MoneyRoute
  '/orders': typeof OrdersRoute
  '/tasks': typeof TasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/brands': typeof BrandsRoute
  '/campaigns': typeof CampaignsRoute
  '/creatives': typeof CreativesRoute
  '/login': typeof LoginRoute
  '/money': typeof MoneyRoute
  '/orders': typeof OrdersRoute
  '/tasks': typeof TasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/brands': typeof BrandsRoute
  '/campaigns': typeof CampaignsRoute
  '/creatives': typeof CreativesRoute
  '/login': typeof LoginRoute
  '/money': typeof MoneyRoute
  '/orders': typeof OrdersRoute
  '/tasks': typeof TasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/brands'
    | '/campaigns'
    | '/creatives'
    | '/login'
    | '/money'
    | '/orders'
    | '/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/brands'
    | '/campaigns'
    | '/creatives'
    | '/login'
    | '/money'
    | '/orders'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/brands'
    | '/campaigns'
    | '/creatives'
    | '/login'
    | '/money'
    | '/orders'
    | '/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  BrandsRoute: typeof BrandsRoute
  CampaignsRoute: typeof CampaignsRoute
  CreativesRoute: typeof CreativesRoute
  LoginRoute: typeof LoginRoute
  MoneyRoute: typeof MoneyRoute
  OrdersRoute: typeof OrdersRoute
  TasksRoute: typeof TasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creatives': {
      id: '/creatives'
      path: '/creatives'
      fullPath: '/creatives'
      preLoaderRoute: typeof CreativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/money': {
      id: '/money'
      path: '/money'
      fullPath: '/money'
      preLoaderRoute: typeof MoneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  BrandsRoute: BrandsRoute,
  CampaignsRoute: CampaignsRoute,
  CreativesRoute: CreativesRoute,
  LoginRoute: LoginRoute,
  MoneyRoute: MoneyRoute,
  OrdersRoute: OrdersRoute,
  TasksRoute: TasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
